apiVersion: v1
kind: Service
metadata:
  name: grpc-server-service
spec:
  type: LoadBalancer
  selector:
    app: grpc-server
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 5001